export const styles = {
  loginScreen: {
    minHeight: '100vh',
    background: '#F5F0E8',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
  },
  loginContainer: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    maxWidth: '900px',
    width: '100%',
    gap: '80px',
    alignItems: 'center',
  },
  loginFormBox: {
    background: 'white',
    padding: '50px 40px',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.05)',
  },
  loginTitle: {
    fontSize: '28px',
    color: '#333',
    marginBottom: '40px',
    fontWeight: '400',
  },
  formGroup: {
    marginBottom: '25px',
  },
  formLabel: {
    display: 'block',
    fontSize: '13px',
    color: '#666',
    marginBottom: '8px',
  },
  formInput: {
    width: '100%',
    padding: '12px',
    border: '1px solid #ddd',
    borderRadius: '4px',
    fontSize: '14px',
    color: '#999',
    outline: 'none',
  },
  btnLogin: {
    width: '100%',
    padding: '14px',
    background: '#D4824B',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
    marginTop: '10px',
    fontWeight: '500',
  },
  forgotLink: {
    display: 'block',
    textAlign: 'left',
    marginTop: '15px',
    fontSize: '13px',
    color: '#666',
    textDecoration: 'underline',
    cursor: 'pointer',
  },
  loginBrand: {
    textAlign: 'center',
  },
  brandIcon: {
    width: '80px',
    height: 'auto',
    margin: '0 auto 20px',
    display: 'block',
  },
  brandName: {
    fontSize: '56px',
    color: '#3D3D3D',
    fontWeight: '300',
    fontStyle: 'italic',
    marginBottom: '5px',
    fontFamily: 'Brush Script MT, cursive',
  },
  brandTagline: {
    fontSize: '16px',
    color: '#D4824B',
    fontStyle: 'italic',
  },
  loginFooter: {
    position: 'fixed',
    bottom: '30px',
    right: '30px',
    display: 'flex',
    gap: '15px',
  },
  footerBtn: {
    background: '#2C2C2C',
    color: 'white',
    padding: '10px 24px',
    border: 'none',
    borderRadius: '4px',
    fontSize: '13px',
    cursor: 'pointer',
  },

  homeScreen: {
    display: 'block',
    minHeight: '100vh',
    background: '#F5F5F5',
  },
  navbar: {
    background: '#2C5F4F',
    padding: '0 40px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '70px',
  },
  navLogo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    color: 'white',
  },
  navIcon: {
    width: '35px',
    height: 'auto',
  },
  navText: {
    fontSize: '22px',
    fontWeight: '300',
    fontStyle: 'italic',
    fontFamily: 'Brush Script MT, cursive',
  },
  navLinks: {
    display: 'flex',
    gap: '35px',
  },
  navLink: {
    color: 'white',
    textDecoration: 'none',
    fontSize: '14px',
    transition: 'opacity 0.3s',
  },
  navActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
  },
  btnSalir: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'transparent',
    border: '1px solid white',
    color: 'white',
    padding: '6px 14px',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '13px',
  },
  userAvatar: {
    width: '38px',
    height: '38px',
    borderRadius: '50%',
    background: '#E89A5F',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '700',
    color: 'white',
    cursor: 'pointer',
    fontSize: '16px',
  },
  mainContent: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '30px 20px',
    display: 'grid',
    gridTemplateColumns: '1fr 380px',
    gap: '25px',
  },
  heroCard: {
    background: '#2C5F4F',
    borderRadius: '16px',
    padding: '35px',
    color: 'white',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    overflow: 'hidden',
  },
  heroContent: {},
  heroTitle: {
    fontSize: '32px',
    fontWeight: '600',
    marginBottom: '8px',
  },
  heroPrice: {
    fontSize: '24px',
    fontWeight: '600',
    margin: '12px 0 20px 0',
    color: '#E8A839',
  },
  btnOrder: {
    background: 'white',
    color: '#5A8277',
    padding: '10px 26px',
    border: 'none',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '14px',
  },
  heroImage: {
    width: '280px',
    height: '200px',
    background: 'white',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '80px',
    transform: 'translateY(60px)',
    opacity: 0.7,
  },
  categoriesSection: {
    background: 'white',
    padding: '25px',
    borderRadius: '12px',
    marginBottom: '20px',
  },
  sectionTitle: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#333',
    marginBottom: '18px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  categoriesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '12px',
  },
  categoryItem: {
    textAlign: 'center',
    padding: '18px 10px',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  categoryIcon: {
    fontSize: '42px',
    marginBottom: '8px',
  },
  categoryName: {
    fontSize: '12px',
    color: '#333',
    fontWeight: '500',
  },
  popularSection: {
    background: 'white',
    padding: '25px',
    borderRadius: '12px',
  },
   popularItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
    padding: '12px',
    borderRadius: '10px',
    marginBottom: '10px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  popularImage: {
    width: '70px',
    height: '70px',
    background: 'linear-gradient(135deg, #FFE8CC, #FFD9A3)',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    fontSize: '40px',
  },
  popularInfo: {
    flex: 1,
  },
  popularName: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#333',
    marginBottom: '6px',
  },
  popularDiscount: {
    fontSize: '12px',
    color: '#999',
    textDecoration: 'line-through',
    marginBottom: '2px',
  },
  popularPrice: {
    fontSize: '15px',
    fontWeight: '700',
    color: '#D4824B',
  },
  btnAdd: {
    width: '34px',
    height: '34px',
    background: '#E89A5F',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '20px',
    cursor: 'pointer',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sidebar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  calendarWidget: {
    background: 'white',
    padding: '22px',
    borderRadius: '12px',
  },
  calendarHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '18px',
  },
  monthName: {
    fontSize: '15px',
    fontWeight: '700',
    color: '#333',
  },
  calendarNav: {
    display: 'flex',
    gap: '6px',
  },
  navArrow: {
    width: '26px',
    height: '26px',
    background: '#f5f5f5',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '14px',
    color: '#666',
  },
  calendarGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: '4px',
    textAlign: 'center',
  },
  dayLabel: {
    fontSize: '11px',
    color: '#999',
    fontWeight: '600',
    padding: '6px 0',
  },
  dayCell: {
    aspectRatio: '1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    borderRadius: '6px',
    cursor: 'pointer',
    color: '#333',
  },
  dayCellSelected: {
    background: '#E89A5F',
    color: 'white',
    fontWeight: '600',
  },
  paymentWidget: {
    background: 'white',
    padding: '22px',
    borderRadius: '12px',
  },
  paymentMethods: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  paymentItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 12px',
    border: '1px solid #e5e5e5',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  paymentItemSelected: {
    borderColor: '#D4824B',
    background: '#FFF9F5',
  },
  paymentIconWrapper: {
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentName: {
    fontSize: '13px',
    fontWeight: '500',
    color: '#333',
    flex: 1,
  },
  paymentLogos: {
    display: 'flex',
    gap: '6px',
  },
  paymentLogo: {
    width: '30px',
    height: '20px',
    background: '#f5f5f5',
    borderRadius: '3px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '16px',
  },
  footer: {
    background: '#2C5F4F',
    padding: '35px 20px 20px',
    marginTop: '50px',
  },
  footerContent: {
    maxWidth: '1400px',
    margin: '0 auto',
    display: 'grid',
    gridTemplateColumns: '2fr 1fr 1fr 1fr',
    gap: '40px',
    color: 'white',
    marginBottom: '25px',
  },
  footerLogo: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '12px',
    fontSize: '22px',
    fontStyle: 'italic',
    fontFamily: 'Brush Script MT, cursive',
  },
  footerIcon: {
    width: '30px',
    height: 'auto',
  },
  footerDescription: {
    opacity: 0.85,
    fontSize: '13px',
    lineHeight: '1.6',
  },
  footerTitle: {
    fontSize: '15px',
    fontWeight: '600',
    marginBottom: '12px',
  },
  footerLink: {
    display: 'block',
    color: 'white',
    opacity: 0.85,
    textDecoration: 'none',
    fontSize: '13px',
    marginBottom: '6px',
  },
  footerBottom: {
    maxWidth: '1400px',
    margin: '0 auto',
    paddingTop: '18px',
    borderTop: '1px solid rgba(255,255,255,0.2)',
    textAlign: 'center',
    opacity: 0.7,
    fontSize: '12px',
    color: 'white',
  },
  socialIcons: {
    display: 'flex',
    gap: '8px',
    marginTop: '12px',
  },
  socialIcon: {
    width: '32px',
    height: '32px',
    background: 'rgba(255,255,255,0.15)',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s',
    fontSize: '14px',
  },
};